### ISSUE TITLE
Cats Effect 3 Support

### ISSUE THREAD

**Issue by Jacoby6000** [neotypes/neotypes#480] opened 2022-03-02 20:59 UTC

**Comment by BalmungSan** [comment] 2022-03-02 21:25
The PR is basically ready #329

The problem is that **Monix** does not support **CE3** and we don't want to publish artifacts with different dependencies.
But being honest, after all this time, that is probably the best idea.

@dimafeng WDYT?

**Comment by Jacoby6000** [comment] 2022-03-03 18:17
Oh interesting. I missed that PR and opened up another one :sweat_smile:  https://github.com/neotypes/neotypes/pull/481

The changeset on mine is somehow smaller, though.

I think that Monix not supporting CE3 shouldn't be an issue. As in my PR, we just leave monix on CE2.   It is unlikely people mix effect systems in their apps, so it is unlikely they would want both monix and CE3 support at the same time from this lib.

**Comment by BalmungSan** [comment] 2022-03-03 18:31
> I think that Monix not supporting CE3 shouldn't be an issue. As in my PR, we just leave monix on CE2. It is unlikely people mix effect systems in their apps, so it is unlikely they would want both monix and CE3 support at the same time from this lib.

Yeah that is what I have been thinking too.
Initially I was worried that for some reason someone would include both **neotypes-cats-effect** and **neotypes-monix** and that would result on a weird eviction warning.
But, as you said, that probably will not happen and we have waited for **monix** for too long now.

I am just waiting to see what Dmitry thinks about all this.

**Comment by dimafeng** [comment] 2022-03-03 18:59
Yeah, I think we should leave monix on CE2. It's been almost a year since #329 😅

**Comment by BalmungSan** [comment] 2022-03-08 03:45
Fixed by [v0.19.0](4186af27339121fa22f0fbcc3527e540c92b4ce2)

**Closed by BalmungSan** 2022-03-08 03:45 UTC
