### ISSUE TITLE
Neotypes Showcase is not working for version "0.15.1"

### ISSUE THREAD

**Issue by dMitin** [neotypes/neotypes#231] opened 2021-01-11 18:06 UTC
import neotypes.generic.auto._
is not resolved, and in request
val people = "match (p:Person) return p.name, p.born limit 10".query[(String, Int)].list(session)

additional implicits are required

**Comment by BalmungSan** [comment] 2021-01-11 21:26
Hi @dMitin similar to #209 the problem is that the site is published for master and the code has changed.

I am sorry about that, we wanted to publish `0.16.0` before and fix the site problem before but we are blocked until #221 gets merged.

**Comment by dMitin** [comment] 2021-01-12 09:29
Thanks for response!
So, we can close ticket.

**Closed** 2021-01-12 12:04 UTC
